osx_image: xcode7.1
sudo: false
language: objective-c
podfile: Example/Podfile
before_script:
- cd Example && pod install && cd -
script:
- set -o pipefail && xcodebuild build -workspace Example/WordPressApiExample.xcworkspace -scheme WordPressApiExample -sdk iphonesimulator | xcpretty -c



